### ISSUE TITLE
Is it possible to re-encrypt the output of Signal-Backup-Decrypt?

### ISSUE THREAD

**Issue by ijesaboy** [gauravmm/Signal-Backup-Decrypt#1]
Hi @gauravmm, Thanks for sharing this Signal-Backup-Decrypt project!

I ended up with a lot of duplication in my signal messages from smsbackup restore imports.

I'm planning to use it to decrypt my signal backup so I can remove duplicate sms without losing mms. Once I've done that, I'd like to clean install signal but ideally from this modified backup file.

Is it possible to re-encrypt the backup after editing?

Otherwise, can you recommend other ways I might achieve my goal remove duplicate sms/mms?

Thanks

**Comment by gauravmm** [comment]
This software package doesn't support that, but you could implement that by copying the relevant parts of the Signal source code.
